version: "3.0"
services:
  web:
    build: ./app/
    volumes:
      - "./app:/src/app"
    ports:
      - "3030:3000"

  moses_api:
    build: ./Moses-API/

    volumes:
      - data-volume:/var/lib/moses_api_backup
    ports:
      - "5000:5000"

volumes:
  data-volume:
