version: "3.0"
services:
  web:
    image: localhost:9000/mtttweb_web
    volumes:
      - "./app:/src/app"
    ports:
      - "3030:3000"

  moses_api:
    image: localhost:9000/mtttweb_moses_api
    volumes:
      - data-volume:/var/lib/moses_api_backup
    ports:
      - "5000:5000"

volumes:
  data-volume:

#localhost:9000 is used as a local repository for the docker images
#in order to avoid downloading and uploading docker images during development
